### ISSUE TITLE
Add ordernumber in payment

### ISSUE THREAD

**Issue by rodneylont10** [dutchbase/Bunq-Wordpress-Woocommerce-Betaling#1]
Great plugin!! Is it possible to add the ordernumber in the payment?

**Comment by dutchbase** [comment]
I tried, the bunq.me/username has the option to put in a description but that does not end up on the transaction details. So yes, it's easy to add the order number but it won't do anything. 

I am also doing all payment confirmation order updates manually :(

**Comment by dutchbase** [comment]
> Great plugin!! Is it possible to add the ordernumber in the payment?

I tried, the bunq.me/username has the option to put in a description but that does not end up on the transaction details. So yes, it's easy to add the order number but it won't do anything.

I am also doing all payment confirmation order updates manually :(
