### ISSUE TITLE
Betaalknop

### ISSUE THREAD

**Issue by VDSER** [dutchbase/Bunq-Wordpress-Woocommerce-Betaling#3]
Is het mogelijk om de betaalknop hoger te plaatsen zodat deze direct zichtbaar is, zonder dat men na onder hoeft te scrollen om de betaalknop te "vinden"?

Dit zal de gebruiksvriendelijkheid, maar ook de conversie aanzienlijk verhogen :)

![Screenshot_58](https://github.com/user-attachments/assets/840b0d12-7d1d-4006-bfb2-1dca4fac0d4a)
![Screenshot_59](https://github.com/user-attachments/assets/d44b2b8d-cfbc-482f-a570-276035fc739c)

**Comment by dutchbase** [comment]
Goeie ja, ik had de mobiele versie nog niet eens bekeken! Ik zal dit zsm
updaten.

Op di 1 okt. 2024 13:36 schreef VDSER ***@***.***>:

**Comment by Zyzz61** [comment]
Hey dutchbase. Ik was benieuwd of je betaalknop hoger heb kunnen plaatsen. Zo ja, moet ik deze plugin opnieuw downloaden?

**Comment by dutchbase** [comment]
Hij is geupate! opnieuw downloaden en installeren.

**Comment by Zyzz61** [comment]
Hoi Dutchbase,

Ik gebruik je bunq plugin al een tijd en ben er super blij mee, dankjewel voor je werk!

Ik heb ook een Mollie betaallink en vroeg me af of het mogelijk is om een vergelijkbare plugin voor Mollie te maken, met dezelfde logica als de bunq plugin. Zoals de groene betaallink op de bedankt pagina die naar payment gateway verwijst. Ik ben ook bereid te betalen voor je tijd en moeite.

Laat me weten wat je ervan denkt!
